//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediscan_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Service { get; set; }
        public int ÙserId { get; set; }
        public int CentreId { get; set; }
    
        public virtual Ùser Ùser { get; set; }
        public virtual Centre Centre { get; set; }
    }
}
